# Netlify deployment configuration for SkyScope Pro Client

[build]
  publish = "dist"
  command = "npm ci --legacy-peer-deps && npm run build"
  base = "client"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Performance optimizations
[[headers]]
  for = "/static/*"
  [headers.values]
    cache-control = "max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    cache-control = "max-age=31536000"
    
[[headers]]
  for = "*.css"
  [headers.values]
    cache-control = "max-age=31536000"
