services:
  - type: web
    name: skyscope-pro-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: WEATHER_API_KEY
        sync: false  # This will be set manually in Render dashboard
    autoDeploy: true
    branch: main
    rootDir: ./
    scaling:
      minInstances: 1
      maxInstances: 3
